# Generated by Django 5.0.6 on 2024-06-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
    ]
