# Generated by Django 5.0.6 on 2024-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aboutus_category_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
    ]
