# Generated by Django 5.0.6 on 2024-06-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_category_post_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categorys',
            new_name='category',
        ),
    ]
