# Generated by Django 5.0.6 on 2024-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_categorys_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
